---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.builder.ContainerName }}-deployment
  labels:
    app: {{ .Values.builder.ContainerName }}
  namespace: {{ .Values.global.Namespace }}
spec:
  replicas: {{ default 1 .Values.builder.NumberOfReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.builder.ContainerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.builder.ContainerName }}
      {{ if .Values.builder.DataVaultMountPoint }}
      annotations:
        vault.security.banzaicloud.io/vault-path: {{ .Values.builder.DataVaultMountPoint }}
        vault.security.banzaicloud.io/vault-role: {{ .Values.builder.DataVaultRole}}
      {{ end }}
    spec:
      serviceAccountName: {{ .Values.builder.ServiceAccountName }}
      containers:
      - name: {{ .Values.builder.ContainerName }}
        image: {{ .Values.builder.Image }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ default "800Mi" .Values.builder.MemoryRequest }}
            cpu:  {{ default "0.4" .Values.builder.CpuRequest }}
          limits:
            memory: {{ default "900Mi" .Values.builder.MemoryLimit }}
            cpu: {{ default "0.6" .Values.builder.CpuLimit }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ps aux | grep python3 | grep -v grep
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ps aux | grep python3 | grep -v grep
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 15
        env:
          - name: "QUEUE_USER"
            value: "{{ .Values.builder.Env.QUEUE_USER }}"
          - name: "QUEUE_PASS"
            value: "{{ .Values.builder.Env.QUEUE_PASS }}"
          - name: "QUEUE_SERVER"
            value: "{{ .Values.builder.Env.QUEUE_SERVER }}"
          - name: "QUEUE_PORT"
            value: "{{ .Values.builder.Env.QUEUE_PORT }}"
          - name: "QUEUE_IN"
            value: "{{ .Values.builder.Env.QUEUE_IN }}"
          - name: "QUEUE_OUT"
            value: "{{ .Values.builder.Env.QUEUE_OUT }}"
          - name: "VSPHERE_SERVER"
            value: "{{ .Values.builder.Env.VSPHERE_SERVER }}"
          - name: "VSPHERE_USER"
            value: "{{ .Values.builder.Env.VSPHERE_USER }}"
          - name: "VSPHERE_PASSWORD"
            value: "{{ .Values.builder.Env.VSPHERE_PASSWORD }}"
          - name: PACKER_LOG
            value: "1"
          - name: PACKER_LOG_PATH
            value: "/var/log/packer.log"
